./csrc/difftest.cpp
./csrc/mem.cpp
./csrc/sim_main.cpp
./vsrc/core/lsu.v
./vsrc/core/regfile.v
./vsrc/core/dfu.v
./vsrc/core/tb.sv
./vsrc/core/exu/alu.v
./vsrc/core/exu/lsu.v
./vsrc/core/exu/muldiv.v
./vsrc/core/exu/csr.v
./vsrc/core/exu/branch.v
./vsrc/core/exu/exu_top.v
./vsrc/core/clk_div.v
./vsrc/core/info_pipeline.v
./vsrc/core/pc_gen.v
./vsrc/core/ifu.v
./vsrc/core/wbu.v
./vsrc/core/raw.v
./vsrc/core/include/defines.v
./vsrc/core/core_top.v
